{% set name = "fast_dp" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower|replace("-", "_") }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e959e96a9e0ec5f99e4391dd839e0e7dfb5b8ce76e1d438649afc216f0f884f0

build:
  noarch: python
  number: 0
  entry_points:
    - fast_dp = fast_dp.fast_dp:main
    - fast_rdp = fast_dp.fast_rdp:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fast_dp

about:
  home: https://github.com/DiamondLightSource/fast_dp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Fast DP: Fast Data Processsing with XDS'
  description: |
    Fast DP is a small Python program which uses XDS, CCP4 & CCTBX
    to very quickly deliver data processing results for single-crystal
    X-ray crystallography experiments.
    Please note that you need to install XDS, CCP4, and CCTBX manually
    as they are not available as conda-forge packages.
  doc_url: https://github.com/DiamondLightSource/fast_dp#fast-dp-fast-data-processsing-with-xds
  dev_url: https://github.com/DiamondLightSource/fast_dp

extra:
  recipe-maintainers:
    - ndevenish
    - Anthchirp
