{% set name = "fast_dp" %}
{% set version = "1.7" %}

package:
  name: {{ name|lower|replace("-", "_") }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ade6bf3d398a80e169980e8ae608bf20e883c1094a2062665f3cc1dc273e99f5
  patches:
    - procrunner.diff

build:
  noarch: python
  number: 0
  entry_points:
    - fast_dp = fast_dp.fast_dp:main
    - fast_rdp = fast_dp.fast_rdp:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - dxtbx

test:
  imports:
    - fast_dp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DiamondLightSource/fast_dp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Fast DP: Fast Data Processsing with XDS'
  description: |
    Fast DP is a small Python program which uses XDS, CCP4 & CCTBX
    to very quickly deliver data processing results for single-crystal
    X-ray crystallography experiments.
    Please note that you need to install XDS, CCP4, and CCTBX manually
    as they are not available as conda-forge packages.
  doc_url: https://github.com/DiamondLightSource/fast_dp#fast-dp-fast-data-processsing-with-xds
  dev_url: https://github.com/DiamondLightSource/fast_dp

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - Anthchirp
